{
 "title": "LOGISNEXT — REGISTRO",
 "description": "Historial de pruebas de la jaula de elevación, tiempos registrados y KPIs de OEE",
 "tags": [
  "mes",
  "log",
  "pruebas",
  "oee"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "selected_bastidor",
    "label": "Bastidor",
    "query": "SELECT DISTINCT NBASTIDOR FROM LOG_TABLA ORDER BY NBASTIDOR"
   }
  ]
 },
 "panels": [
  {
   "title": "🟢 REGISTRO DETALLADO DE PRUEBAS OK",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\n  id AS id,\n  OPERARIO AS OPERARIO,\n  COALESCE(CONVERT(varchar(10), TRY_CAST(FECHA_MONTAJE AS DATE), 103), '') AS FECHA_MONTAJE,\n  NSECUENCIA AS NSECUENCIA,\n  NMODELO AS NMODELO,\n  NBASTIDOR AS NBASTIDOR,\n  OK_NOK AS OK_NOK,\n  NMASTIL AS NMASTIL,\n  ALTURA_MAX_INTERMEDIA AS ALTURA_MAX_INTERMEDIA,\n  ESTADO_MULTILOAD AS ESTADO_MULTILOAD,\n  TIEMPO_ELEVACION_MIN_SINCARGA AS TIEMPO_ELEVACION_MIN_SINCARGA,\n  TIEMPO_ELEVACION_MAX_SINCARGA AS TIEMPO_ELEVACION_MAX_SINCARGA,\n  CASE\n    WHEN TIEMPO_ELEVACION_MEDIDO_SINCARGA IS NULL THEN ''\n    WHEN TIEMPO_ELEVACION_MIN_SINCARGA IS NULL OR TIEMPO_ELEVACION_MAX_SINCARGA IS NULL\n    THEN CAST(CAST(TIEMPO_ELEVACION_MEDIDO_SINCARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n    WHEN TIEMPO_ELEVACION_MEDIDO_SINCARGA >= TIEMPO_ELEVACION_MIN_SINCARGA\n     AND TIEMPO_ELEVACION_MEDIDO_SINCARGA <= TIEMPO_ELEVACION_MAX_SINCARGA\n    THEN N'🟢 ' + CAST(CAST(TIEMPO_ELEVACION_MEDIDO_SINCARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n    ELSE N'🔴 ' + CAST(CAST(TIEMPO_ELEVACION_MEDIDO_SINCARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n  END AS TIEMPO_ELEVACION_MEDIDO_SINCARGA,\n  TIEMPO_DESCENSO_MIN_SINCARGA AS TIEMPO_DESCENSO_MIN_SINCARGA,\n  TIEMPO_DESCENSO_MAX_SINCARGA AS TIEMPO_DESCENSO_MAX_SINCARGA,\n  CASE\n    WHEN TIEMPO_DESCENSO_MEDIDO_SINCARGA IS NULL THEN ''\n    WHEN TIEMPO_DESCENSO_MIN_SINCARGA IS NULL OR TIEMPO_DESCENSO_MAX_SINCARGA IS NULL\n    THEN CAST(CAST(TIEMPO_DESCENSO_MEDIDO_SINCARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n    WHEN TIEMPO_DESCENSO_MEDIDO_SINCARGA >= TIEMPO_DESCENSO_MIN_SINCARGA\n     AND TIEMPO_DESCENSO_MEDIDO_SINCARGA <= TIEMPO_DESCENSO_MAX_SINCARGA\n    THEN N'🟢 ' + CAST(CAST(TIEMPO_DESCENSO_MEDIDO_SINCARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n    ELSE N'🔴 ' + CAST(CAST(TIEMPO_DESCENSO_MEDIDO_SINCARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n  END AS TIEMPO_DESCENSO_MEDIDO_SINCARGA,\n  ESTADO_SINCARGA AS ESTADO_SINCARGA,\n  TIEMPO_ELEVACION_MIN_CARGA AS TIEMPO_ELEVACION_MIN_CARGA,\n  TIEMPO_ELEVACION_MAX_CARGA AS TIEMPO_ELEVACION_MAX_CARGA,\n  CASE\n    WHEN TIEMPO_ELEVACION_MEDIDO_CARGA IS NULL THEN ''\n    WHEN TIEMPO_ELEVACION_MIN_CARGA IS NULL OR TIEMPO_ELEVACION_MAX_CARGA IS NULL\n    THEN CAST(CAST(TIEMPO_ELEVACION_MEDIDO_CARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n    WHEN TIEMPO_ELEVACION_MEDIDO_CARGA >= TIEMPO_ELEVACION_MIN_CARGA\n     AND TIEMPO_ELEVACION_MEDIDO_CARGA <= TIEMPO_ELEVACION_MAX_CARGA\n    THEN N'🟢 ' + CAST(CAST(TIEMPO_ELEVACION_MEDIDO_CARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n    ELSE N'🔴 ' + CAST(CAST(TIEMPO_ELEVACION_MEDIDO_CARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n  END AS TIEMPO_ELEVACION_MEDIDO_CARGA,\n  TIEMPO_DESCENSO_MIN_CARGA AS TIEMPO_DESCENSO_MIN_CARGA,\n  TIEMPO_DESCENSO_MAX_CARGA AS TIEMPO_DESCENSO_MAX_CARGA,\n  CASE\n    WHEN TIEMPO_DESCENSO_MEDIDO_CARGA IS NULL THEN ''\n    WHEN TIEMPO_DESCENSO_MIN_CARGA IS NULL OR TIEMPO_DESCENSO_MAX_CARGA IS NULL\n    THEN CAST(CAST(TIEMPO_DESCENSO_MEDIDO_CARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n    WHEN TIEMPO_DESCENSO_MEDIDO_CARGA >= TIEMPO_DESCENSO_MIN_CARGA\n     AND TIEMPO_DESCENSO_MEDIDO_CARGA <= TIEMPO_DESCENSO_MAX_CARGA\n    THEN N'🟢 ' + CAST(CAST(TIEMPO_DESCENSO_MEDIDO_CARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n    ELSE N'🔴 ' + CAST(CAST(TIEMPO_DESCENSO_MEDIDO_CARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n  END AS TIEMPO_DESCENSO_MEDIDO_CARGA,\n  ESTADO_CARGA AS ESTADO_CARGA,\n  CARGA_CONSIGNADA AS CARGA_CONSIGNADA,\n  CARGA_GET AS CARGA_GET,\n  PESO_PRUEBA AS PESO_PRUEBA,\n  ALTURA_INICIAL AS ALTURA_INICIAL,\n  ALTURA_FINAL AS ALTURA_FINAL,\n  DIFERENCIA_ALTURAS AS DIFERENCIA_ALTURAS,\n  ESTADO_CARGA_5_MIN AS ESTADO_CARGA_5_MIN,\n  FECHA_HORA_INICIO_SEC AS FECHA_HORA_INICIO_SEC,\n  FECHA_HORA_FIN_SEC AS FECHA_HORA_FIN_SEC,\n  DURACION_SEC AS DURACION_SEC\nFROM LOG_TABLA WHERE OK_NOK = 'OK' AND $__timeFilter(fecha_creacion) ORDER BY id DESC"
    }
   ]
  },
  {
   "title": "🔴 REGISTRO DETALLADO DE PRUEBAS NOK",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT\n  id AS id,\n  OPERARIO AS OPERARIO,\n  COALESCE(CONVERT(varchar(10), TRY_CAST(FECHA_MONTAJE AS DATE), 103), '') AS FECHA_MONTAJE,\n  NSECUENCIA AS NSECUENCIA,\n  NMODELO AS NMODELO,\n  NBASTIDOR AS NBASTIDOR,\n  OK_NOK AS OK_NOK,\n  NMASTIL AS NMASTIL,\n  ALTURA_MAX_INTERMEDIA AS ALTURA_MAX_INTERMEDIA,\n  ESTADO_MULTILOAD AS ESTADO_MULTILOAD,\n  TIEMPO_ELEVACION_MIN_SINCARGA AS TIEMPO_ELEVACION_MIN_SINCARGA,\n  TIEMPO_ELEVACION_MAX_SINCARGA AS TIEMPO_ELEVACION_MAX_SINCARGA,\n  CASE\n    WHEN TIEMPO_ELEVACION_MEDIDO_SINCARGA IS NULL THEN ''\n    WHEN TIEMPO_ELEVACION_MIN_SINCARGA IS NULL OR TIEMPO_ELEVACION_MAX_SINCARGA IS NULL\n    THEN CAST(CAST(TIEMPO_ELEVACION_MEDIDO_SINCARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n    WHEN TIEMPO_ELEVACION_MEDIDO_SINCARGA >= TIEMPO_ELEVACION_MIN_SINCARGA\n     AND TIEMPO_ELEVACION_MEDIDO_SINCARGA <= TIEMPO_ELEVACION_MAX_SINCARGA\n    THEN N'🟢 ' + CAST(CAST(TIEMPO_ELEVACION_MEDIDO_SINCARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n    ELSE N'🔴 ' + CAST(CAST(TIEMPO_ELEVACION_MEDIDO_SINCARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n  END AS TIEMPO_ELEVACION_MEDIDO_SINCARGA,\n  TIEMPO_DESCENSO_MIN_SINCARGA AS TIEMPO_DESCENSO_MIN_SINCARGA,\n  TIEMPO_DESCENSO_MAX_SINCARGA AS TIEMPO_DESCENSO_MAX_SINCARGA,\n  CASE\n    WHEN TIEMPO_DESCENSO_MEDIDO_SINCARGA IS NULL THEN ''\n    WHEN TIEMPO_DESCENSO_MIN_SINCARGA IS NULL OR TIEMPO_DESCENSO_MAX_SINCARGA IS NULL\n    THEN CAST(CAST(TIEMPO_DESCENSO_MEDIDO_SINCARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n    WHEN TIEMPO_DESCENSO_MEDIDO_SINCARGA >= TIEMPO_DESCENSO_MIN_SINCARGA\n     AND TIEMPO_DESCENSO_MEDIDO_SINCARGA <= TIEMPO_DESCENSO_MAX_SINCARGA\n    THEN N'🟢 ' + CAST(CAST(TIEMPO_DESCENSO_MEDIDO_SINCARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n    ELSE N'🔴 ' + CAST(CAST(TIEMPO_DESCENSO_MEDIDO_SINCARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n  END AS TIEMPO_DESCENSO_MEDIDO_SINCARGA,\n  ESTADO_SINCARGA AS ESTADO_SINCARGA,\n  TIEMPO_ELEVACION_MIN_CARGA AS TIEMPO_ELEVACION_MIN_CARGA,\n  TIEMPO_ELEVACION_MAX_CARGA AS TIEMPO_ELEVACION_MAX_CARGA,\n  CASE\n    WHEN TIEMPO_ELEVACION_MEDIDO_CARGA IS NULL THEN ''\n    WHEN TIEMPO_ELEVACION_MIN_CARGA IS NULL OR TIEMPO_ELEVACION_MAX_CARGA IS NULL\n    THEN CAST(CAST(TIEMPO_ELEVACION_MEDIDO_CARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n    WHEN TIEMPO_ELEVACION_MEDIDO_CARGA >= TIEMPO_ELEVACION_MIN_CARGA\n     AND TIEMPO_ELEVACION_MEDIDO_CARGA <= TIEMPO_ELEVACION_MAX_CARGA\n    THEN N'🟢 ' + CAST(CAST(TIEMPO_ELEVACION_MEDIDO_CARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n    ELSE N'🔴 ' + CAST(CAST(TIEMPO_ELEVACION_MEDIDO_CARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n  END AS TIEMPO_ELEVACION_MEDIDO_CARGA,\n  TIEMPO_DESCENSO_MIN_CARGA AS TIEMPO_DESCENSO_MIN_CARGA,\n  TIEMPO_DESCENSO_MAX_CARGA AS TIEMPO_DESCENSO_MAX_CARGA,\n  CASE\n    WHEN TIEMPO_DESCENSO_MEDIDO_CARGA IS NULL THEN ''\n    WHEN TIEMPO_DESCENSO_MIN_CARGA IS NULL OR TIEMPO_DESCENSO_MAX_CARGA IS NULL\n    THEN CAST(CAST(TIEMPO_DESCENSO_MEDIDO_CARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n    WHEN TIEMPO_DESCENSO_MEDIDO_CARGA >= TIEMPO_DESCENSO_MIN_CARGA\n     AND TIEMPO_DESCENSO_MEDIDO_CARGA <= TIEMPO_DESCENSO_MAX_CARGA\n    THEN N'🟢 ' + CAST(CAST(TIEMPO_DESCENSO_MEDIDO_CARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n    ELSE N'🔴 ' + CAST(CAST(TIEMPO_DESCENSO_MEDIDO_CARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n  END AS TIEMPO_DESCENSO_MEDIDO_CARGA,\n  ESTADO_CARGA AS ESTADO_CARGA,\n  CARGA_CONSIGNADA AS CARGA_CONSIGNADA,\n  CARGA_GET AS CARGA_GET,\n  PESO_PRUEBA AS PESO_PRUEBA,\n  ALTURA_INICIAL AS ALTURA_INICIAL,\n  ALTURA_FINAL AS ALTURA_FINAL,\n  DIFERENCIA_ALTURAS AS DIFERENCIA_ALTURAS,\n  ESTADO_CARGA_5_MIN AS ESTADO_CARGA_5_MIN,\n  FECHA_HORA_INICIO_SEC AS FECHA_HORA_INICIO_SEC,\n  FECHA_HORA_FIN_SEC AS FECHA_HORA_FIN_SEC,\n  DURACION_SEC AS DURACION_SEC\nFROM LOG_TABLA WHERE OK_NOK = 'NOK' AND $__timeFilter(fecha_creacion) ORDER BY id DESC"
    }
   ]
  },
  {
   "title": "📋 LISTADO DE SECUENCIAS",
   "type": "table",
   "gridPos": { "h": 30, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  id AS id,\n  OPERARIO AS OPERARIO,\n  COALESCE(CONVERT(varchar(10), TRY_CAST(FECHA_MONTAJE AS DATE), 103), '') AS FECHA_MONTAJE,\n  NSECUENCIA AS NSECUENCIA,\n  NMODELO AS NMODELO,\n  NBASTIDOR AS NBASTIDOR,\n  OK_NOK AS OK_NOK,\n  NMASTIL AS NMASTIL,\n  ALTURA_MAX_INTERMEDIA AS ALTURA_MAX_INTERMEDIA,\n  ESTADO_MULTILOAD AS ESTADO_MULTILOAD,\n  TIEMPO_ELEVACION_MIN_SINCARGA AS TIEMPO_ELEVACION_MIN_SINCARGA,\n  TIEMPO_ELEVACION_MAX_SINCARGA AS TIEMPO_ELEVACION_MAX_SINCARGA,\n  CASE\n    WHEN TIEMPO_ELEVACION_MEDIDO_SINCARGA IS NULL THEN ''\n    WHEN TIEMPO_ELEVACION_MIN_SINCARGA IS NULL OR TIEMPO_ELEVACION_MAX_SINCARGA IS NULL\n    THEN CAST(CAST(TIEMPO_ELEVACION_MEDIDO_SINCARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n    WHEN TIEMPO_ELEVACION_MEDIDO_SINCARGA >= TIEMPO_ELEVACION_MIN_SINCARGA\n     AND TIEMPO_ELEVACION_MEDIDO_SINCARGA <= TIEMPO_ELEVACION_MAX_SINCARGA\n    THEN N'🟢 ' + CAST(CAST(TIEMPO_ELEVACION_MEDIDO_SINCARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n    ELSE N'🔴 ' + CAST(CAST(TIEMPO_ELEVACION_MEDIDO_SINCARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n  END AS TIEMPO_ELEVACION_MEDIDO_SINCARGA,\n  TIEMPO_DESCENSO_MIN_SINCARGA AS TIEMPO_DESCENSO_MIN_SINCARGA,\n  TIEMPO_DESCENSO_MAX_SINCARGA AS TIEMPO_DESCENSO_MAX_SINCARGA,\n  CASE\n    WHEN TIEMPO_DESCENSO_MEDIDO_SINCARGA IS NULL THEN ''\n    WHEN TIEMPO_DESCENSO_MIN_SINCARGA IS NULL OR TIEMPO_DESCENSO_MAX_SINCARGA IS NULL\n    THEN CAST(CAST(TIEMPO_DESCENSO_MEDIDO_SINCARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n    WHEN TIEMPO_DESCENSO_MEDIDO_SINCARGA >= TIEMPO_DESCENSO_MIN_SINCARGA\n     AND TIEMPO_DESCENSO_MEDIDO_SINCARGA <= TIEMPO_DESCENSO_MAX_SINCARGA\n    THEN N'🟢 ' + CAST(CAST(TIEMPO_DESCENSO_MEDIDO_SINCARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n    ELSE N'🔴 ' + CAST(CAST(TIEMPO_DESCENSO_MEDIDO_SINCARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n  END AS TIEMPO_DESCENSO_MEDIDO_SINCARGA,\n  ESTADO_SINCARGA AS ESTADO_SINCARGA,\n  TIEMPO_ELEVACION_MIN_CARGA AS TIEMPO_ELEVACION_MIN_CARGA,\n  TIEMPO_ELEVACION_MAX_CARGA AS TIEMPO_ELEVACION_MAX_CARGA,\n  CASE\n    WHEN TIEMPO_ELEVACION_MEDIDO_CARGA IS NULL THEN ''\n    WHEN TIEMPO_ELEVACION_MIN_CARGA IS NULL OR TIEMPO_ELEVACION_MAX_CARGA IS NULL\n    THEN CAST(CAST(TIEMPO_ELEVACION_MEDIDO_CARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n    WHEN TIEMPO_ELEVACION_MEDIDO_CARGA >= TIEMPO_ELEVACION_MIN_CARGA\n     AND TIEMPO_ELEVACION_MEDIDO_CARGA <= TIEMPO_ELEVACION_MAX_CARGA\n    THEN N'🟢 ' + CAST(CAST(TIEMPO_ELEVACION_MEDIDO_CARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n    ELSE N'🔴 ' + CAST(CAST(TIEMPO_ELEVACION_MEDIDO_CARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n  END AS TIEMPO_ELEVACION_MEDIDO_CARGA,\n  TIEMPO_DESCENSO_MIN_CARGA AS TIEMPO_DESCENSO_MIN_CARGA,\n  TIEMPO_DESCENSO_MAX_CARGA AS TIEMPO_DESCENSO_MAX_CARGA,\n  CASE\n    WHEN TIEMPO_DESCENSO_MEDIDO_CARGA IS NULL THEN ''\n    WHEN TIEMPO_DESCENSO_MIN_CARGA IS NULL OR TIEMPO_DESCENSO_MAX_CARGA IS NULL\n    THEN CAST(CAST(TIEMPO_DESCENSO_MEDIDO_CARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n    WHEN TIEMPO_DESCENSO_MEDIDO_CARGA >= TIEMPO_DESCENSO_MIN_CARGA\n     AND TIEMPO_DESCENSO_MEDIDO_CARGA <= TIEMPO_DESCENSO_MAX_CARGA\n    THEN N'🟢 ' + CAST(CAST(TIEMPO_DESCENSO_MEDIDO_CARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n    ELSE N'🔴 ' + CAST(CAST(TIEMPO_DESCENSO_MEDIDO_CARGA AS DECIMAL(10,2)) AS VARCHAR) + ' s'\n  END AS TIEMPO_DESCENSO_MEDIDO_CARGA,\n  ESTADO_CARGA AS ESTADO_CARGA,\n  CARGA_CONSIGNADA AS CARGA_CONSIGNADA,\n  CARGA_GET AS CARGA_GET,\n  PESO_PRUEBA AS PESO_PRUEBA,\n  ALTURA_INICIAL AS ALTURA_INICIAL,\n  ALTURA_FINAL AS ALTURA_FINAL,\n  DIFERENCIA_ALTURAS AS DIFERENCIA_ALTURAS,\n  ESTADO_CARGA_5_MIN AS ESTADO_CARGA_5_MIN,\n  FECHA_HORA_INICIO_SEC AS FECHA_HORA_INICIO_SEC,\n  FECHA_HORA_FIN_SEC AS FECHA_HORA_FIN_SEC,\n  DURACION_SEC AS DURACION_SEC\nFROM LOG_TABLA WHERE ('${selected_bastidor:raw}' = 'ALL' OR NBASTIDOR = '${selected_bastidor:raw}') ORDER BY NSECUENCIA ASC, id DESC"
    }
   ]
  },
  {
   "title": "📊 RESUMEN DE PRODUCCIÓN POR TIPO DE MÁQUINA (OK / NOK)",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CONCAT(\n    CASE\n      WHEN NMODELO LIKE 'XL%' THEN 'XL'\n      WHEN NMODELO LIKE 'MX%' THEN 'M2'\n      WHEN NMODELO LIKE 'FD%' OR NMODELO LIKE 'FG%' THEN 'M11'\n      ELSE 'Otros'\n    END,\n    ' - ',\n    OK_NOK\n  ) AS [Tipo Máquina],\n  COUNT(*) AS [Cantidad]\nFROM LOG_TABLA\nWHERE (NMODELO LIKE 'XL%' OR NMODELO LIKE 'MX%' OR NMODELO LIKE 'FD%' OR NMODELO LIKE 'FG%')\n  AND $__timeFilter(fecha_creacion)\nGROUP BY\n  CASE\n    WHEN NMODELO LIKE 'XL%' THEN 'XL'\n    WHEN NMODELO LIKE 'MX%' THEN 'M2'\n    WHEN NMODELO LIKE 'FD%' OR NMODELO LIKE 'FG%' THEN 'M11'\n    ELSE 'Otros'\n  END,\n  OK_NOK"
    }
   ]
  }
 ]
}