import pyodbc

conn_str = (
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=DESKTOP-PMRMSPT\\SQLEXPRESS,1435;"
    "DATABASE=DAFEED;"
    "UID=usuario_readonly;"
    "PWD=Logisnext2026!;"
    "TrustServerCertificate=yes;"
)
conn = pyodbc.connect(conn_str)
cursor = conn.cursor()
cursor.execute("""
SELECT id, 
  TIEMPO_ELEVACION_MEDIDO_SINCARGA, TIEMPO_ELEVACION_MIN_SINCARGA, TIEMPO_ELEVACION_MAX_SINCARGA,
  TIEMPO_DESCENSO_MEDIDO_SINCARGA, TIEMPO_DESCENSO_MIN_SINCARGA, TIEMPO_DESCENSO_MAX_SINCARGA
FROM LOG_TABLA
WHERE 
  TIEMPO_ELEVACION_MEDIDO_SINCARGA < TIEMPO_ELEVACION_MIN_SINCARGA OR
  TIEMPO_ELEVACION_MEDIDO_SINCARGA > TIEMPO_ELEVACION_MAX_SINCARGA OR
  TIEMPO_DESCENSO_MEDIDO_SINCARGA < TIEMPO_DESCENSO_MIN_SINCARGA OR
  TIEMPO_DESCENSO_MEDIDO_SINCARGA > TIEMPO_DESCENSO_MAX_SINCARGA
ORDER BY id DESC
""")
rows = cursor.fetchall()
for r in rows[:10]:
    print(f"ID: {r[0]} | Elev Med: {r[1]}, Min: {r[2]}, Max: {r[3]} | Desc Med: {r[4]}, Min: {r[5]}, Max: {r[6]}")
